 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Akonaditray", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"GPG-Crypter", "gpg-crypter", "/usr/share/pixmaps/gpg-crypter.png" },
     {"Leafpad", "leafpad ", "/usr/share/icons/hicolor/16x16/apps/leafpad.png" },
     {"Passwords and Keys", "/usr/bin/seahorse", "/usr/share/icons/hicolor/16x16/apps/seahorse.png" },
     {"QStarDict", "qstardict", "/usr/share/pixmaps/qstardict.png" },
     {"Qalculate!", "qalculate-gtk", "/usr/share/pixmaps/qalculate.png" },
     {"Root Terminal", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"Weboob backends configuration", "weboob-config-qt", "/usr/share/icons/hicolor/64x64/apps/weboob-config-qt.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"GNU TeXmacs", "texmacs ", "/usr/share/pixmaps/TeXmacs.xpm" },
     {"GoldenDict", "goldendict", "///usr/share/pixmaps/goldendict.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"FEZ", "\"/home/kure/games/fez/FEZ\"", "///home/kure/games/fez/FEZ.bmp" },
     {"Golly", "golly", "/usr/share/pixmaps/golly.xpm" },
     {"vitetris", "xterm -e tetris -w 80", "/usr/share/pixmaps/vitetris.xpm" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"EasyPaint", "easypaint ", "/usr/share/pixmaps/easypaint_64.png" },
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"GrafX2", "grafx2 ", "/usr/share/icons/grafx2.xpm" },
     {"Image Viewer", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
     {"PabloDraw", "pablodraw"},
     {"Tiled", "tiled", "/usr/share/icons/hicolor/16x16/apps/tiled.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Anomos", "anondownloadgui", "/usr/share/pixmaps/anomos.png" },
     {"Arora", "arora ", "/usr/share/icons/hicolor/16x16/apps/arora.png" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Blogbridge", "blogbridge", "///usr/share/pixmaps/blogbridge.gif" },
     {"Browse Mirrored Websites", "webhttrack browse", "/usr/share/icons/hicolor/16x16/apps/httrack.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Dropbox", "dropboxd", "/usr/share/pixmaps/dropbox.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share/icons/gnome/16x16/mimetypes/html.png" },
     {"Ettercap", "ettercap-pkexec -G", "/usr/share/pixmaps/ettercap.svg" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Great Little Radio Player", "/opt/extras.ubuntu.com/glrp/GreatLittleRadioPlayer", "///opt/extras.ubuntu.com/glrp/glrp.svg" },
     {"HexChat", "hexchat ", "/usr/share/icons/hicolor/48x48/apps/hexchat.png" },
     {"Liferea", "liferea", "/usr/share/icons/hicolor/16x16/apps/liferea.png" },
     {"Lightweight2", "lightweight2 ", "/usr/share/pixmaps/lightweight2.png" },
     {"LinuxDC++", "linuxdcpp", "/usr/share/icons/hicolor/16x16/apps/linuxdcpp.png" },
     {"Luakit", "luakit ", "/usr/share/pixmaps/luakit.png" },
     {"Masstransit", "masstransit", "/usr/share/icons/hicolor/64x64/apps/masstransit.png" },
     {"Midori", "midori ", "/usr/share/icons/hicolor/16x16/apps/midori.png" },
     {"Midori Private Browsing", "midori --private ", "/usr/share/icons/hicolor/16x16/apps/midori.png" },
     {"Netsurf", "netsurf ", "/usr/share/pixmaps/netsurf.png" },
     {"Nicotine-Plus", "nicotine.py", "/usr/share/pixmaps/nicotine-plus-32px.png" },
     {"NomNom", "/usr/bin/nomnom", "///usr/share/pixmaps/nomnom.xpm" },
     {"Opera", "/usr/bin/opera ", "/usr/share/icons/hicolor/16x16/apps/opera-browser.png" },
     {"Pidgin Internet Messenger", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"QBoobmsg", "qboobmsg", "/usr/share/icons/hicolor/64x64/apps/qboobmsg.png" },
     {"QCineoob", "qcineoob", "/usr/share/icons/hicolor/64x64/apps/qcineoob.png" },
     {"QCookboob", "qcookboob", "/usr/share/icons/hicolor/64x64/apps/qcookboob.png" },
     {"QFlatBoob", "qflatboob", "/usr/share/icons/hicolor/64x64/apps/qflatboob.png" },
     {"QHaveDate", "qhavedate", "/usr/share/icons/hicolor/64x64/apps/qhavedate.png" },
     {"QWebContentEdit", "qwebcontentedit", "/usr/share/icons/hicolor/64x64/apps/qwebcontentedit.png" },
     {"QupZilla", "qupzilla ", "/usr/share/icons/hicolor/16x16/apps/qupzilla.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"TORChat", "/usr/bin/torchat", "/usr/share/pixmaps/torchat.png" },
     {"Thunderbird", "thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"Tor-Browser (en-US)", "/usr/bin/tor-browser-en", "///usr/share/pixmaps/tor-browser-en.png" },
     {"WebHTTrack Website Copier", "webhttrack", "/usr/share/icons/hicolor/16x16/apps/httrack.png" },
     {"Wicd", "/usr/bin/wicd-client", "/usr/share/icons/hicolor/16x16/apps/wicd-gtk.png" },
     {"XChat IRC", "xchat", "/usr/share/icons/hicolor/24x24/apps/xchat.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"opera-mini", "opera-mini"},
     {"qBittorrent", "qbittorrent ", "/usr/share/icons/hicolor/16x16/apps/qbittorrent.png" },
     {"w3af", "/usr/bin/w3af_gui"},
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"AbiWord", "abiword", "/usr/share/icons/abiword_48.png" },
     {"Ascii Design", "ascii-design", "/usr/share/pixmaps/ascii-design.png" },
     {"Document Viewer", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
     {"Ganttproject", "/opt/ganttproject/ganttproject", "///opt/ganttproject/plugins/net.sourceforge.ganttproject/data/resources/logos/icon64.png" },
     {"GoldenDict", "goldendict", "///usr/share/pixmaps/goldendict.png" },
     {"KeepNote", "keepnote ", "/usr/share/icons/hicolor/48x48/apps/keepnote.png" },
     {"Kile", "kile ", "/usr/share/icons/hicolor/16x16/apps/kile.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"StarDict", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"Tomighty", "tomighty", "/usr/share/pixmaps/tomighty.png" },
     {"Wordview Microsoft doc Viewer", "wordview", "/usr/share/pixmaps/wordview.xpm" },
     {"XMind", "/usr/share/xmind/XMind", "/usr/share/pixmaps/xmind.png" },
     {"Zathura", "zathura "},
     {"llpp", "llpp "},
     {"wikidPad", "wikidpad", "/usr/share/pixmaps/wikidpad.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Android SDK", "android", "/usr/share/pixmaps/android-sdk.png" },
     {"Anjuta", "anjuta ", "/usr/share/icons/hicolor/16x16/apps/anjuta.png" },
     {"Arduino", "arduino", "/usr/share/icons/hicolor/256x256/apps/arduino.png" },
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Database browser", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
     {"Devhelp", "devhelp", "/usr/share/icons/hicolor/16x16/apps/devhelp.png" },
     {"Eclipse", "eclipse"},
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"Evan's Debugger", "edb", "/usr/share/icons/hicolor/48x48/apps/edb.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"FlameRobin", "flamerobin", "///usr/share/pixmaps/flamerobin.png" },
     {"Geany", "geany ", "/usr/share/icons/hicolor/16x16/apps/geany.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"KDevelop 4", "kdevelop ", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"KDevelop 4 (Pick Session)", "kdevelop --ps", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"SciTE Text Editor", "SciTE ", "/usr/share/pixmaps/Sci48M.png" },
     {"Umbrello", "umbrello -caption Umbrello", "/usr/share/icons/hicolor/16x16/apps/umbrello.png" },
     {"microemulator", "microemulator", "/usr/share/icons/hicolor/16x16/apps/java.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
     {"Clementine", "clementine ", "/usr/share/icons/hicolor/64x64/apps/application-x-clementine.png" },
     {"DamnVid", "/usr/share/damnvid/DamnVid", "///usr/share/damnvid/img/icon.ico" },
     {"Floola", "floola", "/usr/share/pixmaps/floola.png" },
     {"Gespeaker", "/usr/bin/gespeaker", "///usr/share/gespeaker/data/icons/gespeaker.svg" },
     {"Great Little Radio Player", "/opt/extras.ubuntu.com/glrp/GreatLittleRadioPlayer", "///opt/extras.ubuntu.com/glrp/glrp.svg" },
     {"Hydrogen Drum Machine", "hydrogen ", "/usr/share/pixmaps/h2-icon.svg" },
     {"MilkyTracker", "milkytracker", "/usr/share/pixmaps/milkytracker.png" },
     {"NomNom", "/usr/bin/nomnom", "///usr/share/pixmaps/nomnom.xpm" },
     {"QT V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"QVideoob", "qvideoob", "/usr/share/icons/hicolor/64x64/apps/qvideoob.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"SMPlayer YouTube Browser", "smtube", "/usr/share/icons/hicolor/16x16/apps/smtube.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Bulk Rename", "/usr/lib/Thunar/ThunarBulkRename ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Guymager", "gksudo guymager", "/usr/share/pixmaps/guymager_128.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Nepomuk Backup", "nepomukbackup"},
     {"Nepomuk Cleaner", "nepomukcleaner"},
     {"Ophcrack", "ophcrack", "///usr/share/ophcrack/pixmaps/os.xpm" },
     {"PkgBrowser", "pkgbrowser", "/usr/share/icons/hicolor/48x48/apps/pkgbrowser.png" },
     {"Squirrel Sql", "squirrel-sql", "///usr/share/pixmaps/acorn.ico" },
     {"Termit", "termit", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/Thunar.png" },
     {"Tilda", "tilda", "/usr/share/pixmaps/tilda.png" },
     {"TrueCrypt", "truecrypt", "/usr/share/pixmaps/truecrypt.xpm" },
     {"UNetbootin", "/usr/bin/unetbootin", "/usr/share/icons/hicolor/16x16/apps/unetbootin.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Yakuake", "yakuake", "/usr/share/icons/hicolor/16x16/apps/yakuake.png" },
     {"Yaourt-Gui", "xterm -e yaourt-gui", "/usr/share/pixmaps/yaourtgui.png" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"mrxvt", "mrxvt", "/usr/share/pixmaps/mrxvt.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/terminal.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

